from odoo import fields, models, _


class SalesRouteLicenseActivationWizard(models.TransientModel):
    _name = 'sales.route.license.activation.wizard'
    _description = 'Field Sales License Activation Wizard'

    license_id = fields.Many2one('sales.route.license', required=True)
    activation_code = fields.Text(string='Activation Code', required=True, help='Paste the external activation key generated by the system owner.')

    def action_activate(self):
        self.ensure_one()
        self.license_id.activate_with_code(self.activation_code)
        return {'type': 'ir.actions.client', 'tag': 'reload'}
